/*
 * JFrameDemoOld.java
 *
 * Created on June 13, 2006, 1:53 PM
 */

package swingset3.toplevels;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JToolBar;

/**
 *
 * @author  aim
 */
public class JFrameDemoOld extends javax.swing.JPanel {
    
    /**
     * Creates new form JFrameDemoOld
     */
    public JFrameDemoOld() {
        initComponents(); // init components 
        frame = createFrame();
    }
    
    protected JFrame createFrame() {
 
        //<snip>Create frame and set simple properties
        JFrame frame = new JFrame("Demo JFrame");
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);      
        //</snip>
        
        //<snip>Set Minimized/titlebar icon Image
        //Note: How the image is used is platform-dependent
        ImageIcon frameIcon = new ImageIcon("resources/images/swingingduke.gif");
        frame.setIconImage(frameIcon.getImage());
        //</snip>
        
        //<snip>Make toplevel "busy"
        // busy glasspane is initially invisible
        frame.setGlassPane(new BusyGlass());
        //</snip>

        //<snip>Add a menubar
        JMenuBar menubar = new JMenuBar();
        frame.setJMenuBar(menubar);
        JMenu menu = new JMenu("File");
        menubar.add(menu);
        menu.add("Open");
        menu.add("Save");
        //</snip>
        
        //<snip>Add a horizontal toolbar
        JToolBar toolbar = new JToolBar();
        frame.getContentPane().add(BorderLayout.NORTH, toolbar);
        toolbar.add(new JButton("Toolbar Button"));
        //</snip>
        
        //<snip>Add the content area
        JLabel label = new JLabel("I'm content and a little blue.");
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setPreferredSize(new Dimension(400,300));
        label.setBackground(new Color(197, 216, 236));
        label.setOpaque(true); // labels non-opaque by default
        frame.add(label);
        //snip
        
        //<snip>Add a statusbar
        statusLabel = new JLabel("I show status.");
        statusLabel.setHorizontalAlignment(JLabel.LEADING);
        frame.getContentPane().add(BorderLayout.SOUTH, statusLabel);
        //</snip>
        
        //<snip>Initialize frame's size
        // which will shrink-to-fit its contents
        frame.pack(); 
        //</snip>
        
        return frame;
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        showButton = new javax.swing.JButton();
        busyCheckbox = new javax.swing.JCheckBox();
        jOptionPane1 = new javax.swing.JOptionPane();

        setToolTipText("Demonstrates JFrame, Swing's top-level primary window container.");
        showButton.setText("Show Frame");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        busyCheckbox.setText("Frame busy");
        busyCheckbox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        busyCheckbox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        busyCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                frameBusyStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(busyCheckbox)
                    .add(showButton))
                .addContainerGap(331, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .add(jOptionPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(showButton)
                .add(14, 14, 14)
                .add(busyCheckbox)
                .add(41, 41, 41)
                .add(jOptionPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void frameBusyStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_frameBusyStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_frameBusyStateChanged

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        if (frame.isShowing()) {
            frame.toFront();
        } else {
            frame.setVisible(true);
        }
    }//GEN-LAST:event_showButtonActionPerformed

    private JFrame frame;
    private JLabel statusLabel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox busyCheckbox;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
    
}
